# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yezi_weibo', '0002_auto_20180614_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yezi_weibo.WBText', verbose_name='被评信息')),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yezi_weibo.WBText', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='yezi_weibo.WBUser', verbose_name='用户')),
            ],
        ),
        migrations.CreateModel(
            name='WeiBo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_del', models.BooleanField(default=False, verbose_name='是否删除')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs', to='yezi_weibo.WBText', verbose_name='微博内容')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs', to='yezi_weibo.WBUser', verbose_name='用户')),
            ],
        ),
    ]
