# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-18 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yezi_weibo', '0003_comment_weibo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='wbtext',
            options={'verbose_name': '微博文本', 'verbose_name_plural': '微博文本'},
        ),
        migrations.AlterModelOptions(
            name='wbuser',
            options={'verbose_name': '微博用户', 'verbose_name_plural': '微博用户'},
        ),
        migrations.AlterModelOptions(
            name='weibo',
            options={'verbose_name': '个人微博', 'verbose_name_plural': '个人微博'},
        ),
    ]
