# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yezi_weibo', '0005_auto_20180715_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='评论'),
        ),
    ]
