# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yezi_weibo', '0007_auto_20180715_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='wbuser',
            name='followers',
            field=models.ManyToManyField(to='yezi_weibo.WBUser', verbose_name='关注'),
        ),
    ]
